### ISSUE TITLE
Styling the reactSelect

### ISSUE THREAD

**Issue by jotasolano** [seattleflu/genomic-incidence-tracker#5]
@jameshadfield I noticed you wanted to override some styles of the reactSelect. I went ahead and started that process, but how exactly do we want it to look?

I removed that divider between the placeholder and the arrow to make it look more like Auspice. However, to have a triangle instead of a caret we'd have to replace that svg element (which is totally doable, but I'm not sure if that's what we want).

Relevant code is in [src/components/sidebar/select.js](https://github.com/seattleflu/genomic-incidence-tracker/pull/4/files#diff-4368afefbae92df7eff08a39f76fc7db)

**Comment by jameshadfield** [comment]
In terms of how we want them to look, I think they look pretty good with your PR #4, and wonder if we're better off playing around with these things in inDesign to get the entire sidebar -- including time selections, model options etcetera -- looking great before implementing them in the app.

**Comment by jotasolano** [comment]
I agree with sketching ideas first in InVision and then implementing. We can leave it as is (PR) for now. I'll merge soon

**Comment by jotasolano** [comment]
Merged in https://github.com/seattleflu/genomic-incidence-tracker/pull/4, further enhancements can be made via mockups in InVision and then we can open another issue if necessary
